#!/bin/bash

# Get the name of the docker file (without path)
BUILD_FILE=$(echo Docker/Dockerfile.arm32v7 | cut -d '/' -f 2)


echo 'starting build'
echo ${DOCKERFILE_PATH}
echo ${BUILD_FILE}
echo ${IMAGE_NAME}
docker build \
    -f "${BUILD_FILE}" \
    -t "${IMAGE_NAME}" \
    .