#!/bin/bash
#uname -a
#cat /proc/sys/fs/binfmt_misc/qemu-arm
#apt-get update
#apt-get install -y curl qemu-user-static binfmt-support
#cat /proc/sys/fs/binfmt_misc/qemu-arm
# local copy of qemu binary 
#cp -p $(which qemu-arm-static) .
# downloads a local copy of qemu on docker-hub build machines
#exists in dir/docker/hooks
curl -L https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-aarch64-static --output qemu-aarch64-static
curl -L https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-3/qemu-arm-static     --output qemu-arm-static
